In [35]:
import torch
import torch.nn as nn

In [60]:
inputs = torch.Tensor([[0.,1.], [0.,1.], [1.,0.], [5.,0.]])
labels = torch.Tensor([1,1,0,0]).type(torch.LongTensor)


loss_func = nn.CrossEntropyLoss()
print(loss_func(inputs, labels))


def myCrossEntropyLoss(inputs: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
    r"""
    this function is equal to general Cross Entropy Loss, which is not weighted version.
    """
    loss = 0
    for i in range(len(inputs)):
        denominator = torch.exp(inputs[i]).sum()
        target = labels[i]
        loss += (-torch.log(torch.exp(inputs[i,target])/denominator))
    return loss/len(inputs)

print(myCrossEntropyLoss(inputs, labels))

tensor(0.2366)
tensor(0.2366)


In [52]:
inputs = torch.Tensor([[0.,1.], [0.,1.], [1.,0.], [1.,0.]])
labels = torch.Tensor([1,1,0,0]).type(torch.LongTensor)

logsoftmax = nn.LogSoftmax()
print(logsoftmax(inputs))

nlloss = nn.NLLLoss()
print(nlloss(inputs, labels))

tensor([[-1.3133, -0.3133],
        [-1.3133, -0.3133],
        [-0.3133, -1.3133],
        [-0.3133, -1.3133]])
tensor(-1.)


/tmp/ipykernel_15722/3733811695.py:5: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  print(logsoftmax(inputs))


In [47]:
print(torch.log(inputs.softmax(dim=-1)))
print()

for i in range(len(inputs)):
    denominator = torch.exp(inputs[i]).sum()
    for j in range(len(inputs[i])):
        inputs[i,j] = torch.log(torch.exp(inputs[i,j])/denominator)
print(inputs)
print()

logsoftmax = nn.LogSoftmax()
print(logsoftmax(inputs))

tensor([[-1.3133, -0.3133],
        [-1.3133, -0.3133],
        [-0.3133, -1.3133],
        [-0.3133, -1.3133]])

tensor([[-1.3133, -0.3133],
        [-1.3133, -0.3133],
        [-0.3133, -1.3133],
        [-0.3133, -1.3133]])

tensor([[-1.3133, -0.3133],
        [-1.3133, -0.3133],
        [-0.3133, -1.3133],
        [-0.3133, -1.3133]])
tensor(0.7311)


/tmp/ipykernel_15722/959556421.py:12: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  print(logsoftmax(inputs))
